server:
  port: 8081
error:
include-message: always
#Configuracion de spring
spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://jelani.db.elephantsql.com:5432/otwvohcw?socketTimeout=3
    username: otwvohcw
    password: tauzmtsSqxYuoHQecKTT_Ot0J6SL07H2
    driverClassName: org.postgresql.Driver